---
title: "Learning Objectives TSM_AdvStDaAn"
author: "Micheal Lappert"
date: "31.03.2022"
output: 
  pdf_document:
    toc: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part I

## Week 1
- Review of Multiple Linear Regression 
- You know the Maximum Likelihood Principle

## Week 2
- You understand Akaike's information criterion (AIC) to select 'important' predictor variables
- You know how to handle categorical predictors (factor variables in R)
- You know what multicollinearity is and how to handle it
- You know how to predict 
- You understand cross validation
- You understand the difference between interpolation vs. extrapolation
- You know the difference between predictive vs. descriptive modelling (versus causality) and can explain it

## Week 3
- Understand Weighted Least Squares
- You know how Robust Fitting works
- You can fit Smooth Functions and Additive Models
- You know how to approach Statistical Model Building

## Week 4
- You know the Logistic Regression Model and its applications
- You know how to fit a Logistic Regression in R
- You know how to interpret the parameter of a Logistic Regression

## Week 5
- You know the three elements that define the GLM
- You can identify members of the GLM family
- You know how to fit GLMs in R and know the algorithm underlying it
- You can interpret R output of a GLM fit

## Week 6
- You know what deviances are in GLM
- You can understand AIC is generalised to GLMs
- You know when you can apply Wald-type confidence intervals and when it is better to use deviance based confidence intervals
- You can apply the introduced methods in statistical data analysis using R

## Week 7
- You know what overdispersion is and can identify it
- You can check the model adequacy
- ... and determine which model assumptions, if any, are violated

## Week 8
- You know what a rate models is and how you can analyse it with GLM
- You know how a quasi model extends a GLM and when you can apply it
- You know that conﬁdence tables can be analysed with an extention of GLM
- You know multinomial and ordinal regression and the diﬀerence between these two models
- You can ﬁt these methods to data using R, interpret the results, make inference statements and predictions.